### ISSUE TITLE
git-clone task not created

### ISSUE THREAD

**Issue by joshualucas84** [thesecuresoftwarefactory/ssf#101]
Git-clone task not created during tekton setup

Current Behavior
----------------
Following quick start guide after running 

Step 4: run a new pipeline

`make example-ibm-tutorial`

💌 Message

Pipeline default/build-and-deploy-pipeline can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "git-clone": tasks.tekton.dev "git-clone" not found

Expected Behavior
-----------------
Successful pipeline run 

Possible Solution
-----------------
Task git-clone needs to be created as apart of quick start guide

Steps to Reproduce
------------------

1. Brand new kubernetes cluster
2. run through quickstart guide
3. run `make example-ibm-tutorial`

**Comment by bradbeck** [comment]
@joshualucas84 Can you confirm what git hash you were running the quick start against?

**Comment by joshualucas84** [comment]
@bradbeck Sorry this was a Duh!!! moment for me, my forked repo was out of date with ssf.

**Comment by bradbeck** [comment]
> @bradbeck Sorry this was a Duh!!! moment for me, my forked repo was out of date with ssf.

Not a problem! 😄
