### ISSUE TITLE
How to demo the blockage of a non-signed image

### ISSUE THREAD

**Issue by maorkuriel** [thesecuresoftwarefactory/ssf#108]
I want to demo the use case of running a pipeline and show that the image was signed, and I can run it.
The 2nd step shows that I am trying to run an image, e.g., Nginx ( kubectl run nginx --image=nginx ), and it will fail as I didn't run it via the steps that are required.

Problem/Question
----------------

How can I demo how the system blocks a non-signed image?
Should Kyverno block running container images that were not signed?

 

Can you add more documentation on this topic that will help guide the user on the steps that he needs to take to demo:
1. How are we able to run an image that was signed
2. How a non signed image ( Nginx) is being blocked
3. How to fix the issue and enable the user to run the image

Also, will it be possible to provide guidance on how to execute the demo that @mlieberman85 ran in KubeCon? 
https://www.youtube.com/watch?v=aS_FKrCLh8o&t=632s

Context
-------

**Comment by bradbeck** [comment]
Here's a rough example of signing verification with Kyverno.

Setup minikube and Kyverno.

```bash
make setup-minikube
make setup-kyverno
```

Run a proxy to the minikube registry so we can push images to it. This needs to be run
in a separate shell since it stays running as long a minikube is running.

```bash
make registry-proxy
```

Set some environment variables. One to hold IP of the registry service inside the cluster
(i.e. `REGISTRY_IP`). The second to hold the host IP external of the cluster where we can interact with it via docker (i.e. `HOST_IP`). `HOST_IP` will typically be the IP of the primary network
interface of the host. This IP will also need to be added to `"insecure-registries": [...]` in
your docker config. In my case I added `"insecure-registries": ["192.168.1.0/24"]`.

```bash
export REGISTRY_IP=$(k get svc registry -n kube-system -o jsonpath='{.spec.clusterIP}')
export HOST_IP=192.168.1.37 # <change this to your host IP>
```

Generate a key pair that we can use for signing and verifying images.

```bash
cosign generate-key-pair
```

Modify the Kyverno `verify-image` cluster policy to only allow images signed by our private key from above (`cosign.key`).

```bash
cat > verify-image.yaml <<EOF
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image
spec:
  validationFailureAction: enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: verify-image
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
      - image: "*"
        key: |-
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEt0n8HRzfPOSodWgewdGH6m3HyfCL
          1RR/TNO+01jQOpaZjz5x3b+rvuPW8Tf9G0flRIsEmvX2THsbiZ4Rhg3X4Q==
          -----END PUBLIC KEY-----
EOF
kubectl apply -f verify-image.yaml
```

Test that the cluster policy is working by trying to run `nginx`.

```bash
$ kubectl run nginx --image=nginx
Error from server: admission webhook "mutate.kyverno.svc-fail" denied the request: 

resource Pod/default/nginx was blocked due to the following policies

verify-image:
  verify-image: 'image signature verification failed for docker.io/nginx:latest: signature
    mismatch'
```

Pull the `nginx` image so we can push it into the internal minikube registry.

```bash
docker pull nginx:latest
docker tag nginx:latest "$HOST_IP":8888/nginx-unsigned
docker push "$HOST_IP":8888/nginx-unsigned
docker tag nginx:latest "$HOST_IP":8888/nginx-signed
docker push "$HOST_IP":8888/nginx-signed
```

Sign `.../nginx-signed` with our private key.

```bash
cosign sign --key cosign.key "$HOST_IP":8888/nginx-signed
```

Confirm that `.../nginx-unsigned` doesn't have a signature associated with it in
the registry.

```bash
$ crane ls "$HOST_IP":8888/nginx-unsigned
latest
```

Confirm that `.../nginx-signed` does have a signature associated with it in
the registry.

```bash
$ crane ls "$HOST_IP":8888/nginx-signed
sha256-f3d58e8e62f8e897e13e60fcef9802a6de34c6adc83aa18ca5397fa7d6121a0b.sig
latest
```

Attempt to run the unsigned image.

```bash
$ kubectl run nginx --image="$REGISTRY_IP"/nginx-unsigned
Error from server: admission webhook "mutate.kyverno.svc-fail" denied the request: 

resource Pod/default/nginx was blocked due to the following policies

verify-image:
  verify-image: 'image signature verification failed for 10.107.32.191/nginx-unsigned:latest:
    signature mismatch'
```

Attempt to run the signed image.

```bash
kubectl run nginx --image="$REGISTRY_IP"/nginx-signed
pod/nginx created
```

**Comment by maorkuriel** [comment]
Thanks, @bradbeck. 
This is amazing, and I appreciate your help.

**Comment by maorkuriel** [comment]
any idea why I am getting this error?
```
❯ cosign sign --key cosign.key 10.0.0.16:8888/nginx-signed
error: signing [10.0.0.16:8888/nginx-signed]: getting remote image: GET http://10.0.0.16:8888/v2/nginx-signed/manifests/latest: MANIFEST_UNKNOWN: manifest unknown; map[Tag:latest]
```

I was able to add push the images to the local repository
```
❯ docker image ls
REPOSITORY                           TAG        IMAGE ID       CREATED         SIZE
10.0.0.16:8888/nginx-signed          latest     63eb316dc556   2 weeks ago     134MB
10.0.0.16:8888/nginx-unsigned        latest     63eb316dc556   2 weeks ago     134MB
nginx                                latest     63eb316dc556   2 weeks ago     134MB
k8s.gcr.io/kube-apiserver            v1.22.4    8fdcfcac0b01   4 weeks ago     119MB
k8s.gcr.io/kube-proxy                v1.22.4    9c13f5c7b906   4 weeks ago     97.4MB
k8s.gcr.io/kube-controller-manager   v1.22.4    c748f2606342   4 weeks ago     113MB
k8s.gcr.io/kube-scheduler            v1.22.4    0b8df59b0199   4 weeks ago     49.3MB
gcr.io/k8s-minikube/kicbase          v0.0.28    c3db8807ea16   2 months ago    981MB
docker/desktop-vpnkit-controller     v2.0       2edf9c994f19   7 months ago    19.2MB
docker/desktop-storage-provisioner   v2.0       c027a58fa0bb   7 months ago    39.8MB
k8s.gcr.io/pause                     3.4.1      d055819ed991   11 months ago   484kB
k8s.gcr.io/coredns/coredns           v1.8.0     1a1f05a2cd7c   14 months ago   39.3MB
k8s.gcr.io/etcd                      3.4.13-0   05b738aa1bc6   15 months ago   312MB
```

**Comment by maorkuriel** [comment]
So after researching the issue that I encounter, it looks like cosign doesn't support local registries 
https://github.com/sigstore/cosign/issues/596

@bradbeck, did you use a local registry?

**Comment by dlorenc** [comment]
Cosign should support local registries, which one did you try with?

**Comment by maorkuriel** [comment]
Hi @dlorenc,
This is the version that I am using:
```
❯ cosign version
GitVersion:    v1.2.1
GitCommit:     be15523ac142ba2e2feadb333bb7af294d232b9f
GitTreeState:  clean
BuildDate:     '2021-09-20T17:20:34Z'
GoVersion:     go1.17
Compiler:      gc
Platform:      darwin/arm64
```
My Minikube version:
```
❯ minikube version
minikube version: v1.24.0
commit: 76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b
```

I am using a proxy to the minikube registry with the ssf script
`make registry-proxy
`

I am running the env on my MacBook M1

**Comment by bradbeck** [comment]
> So after researching the issue that I encounter, it looks like cosign doesn't support local registries [sigstore/cosign#596](https://github.com/sigstore/cosign/issues/596)
> 
> @bradbeck, did you use a local registry?

Yes, I used Minikube's internal registry.

**Comment by bradbeck** [comment]
> Any idea why I am getting this error? I followed the instructions, and I have no idea what is causing this error.
> 
> ```
> ❯ cosign sign --key cosign.key 10.0.0.16:8888/nginx-signed
> error: signing [10.0.0.16:8888/nginx-signed]: getting remote image: GET http://10.0.0.16:8888/v2/nginx-signed/manifests/latest: MANIFEST_UNKNOWN: manifest unknown; map[Tag:latest]
> ```
> 
> I was able to add push the images to the local repository.
> 
> ```
> ❯ docker image ls
> REPOSITORY                           TAG        IMAGE ID       CREATED         SIZE
> 10.0.0.16:8888/nginx-signed          latest     63eb316dc556   2 weeks ago     134MB
> 10.0.0.16:8888/nginx-unsigned        latest     63eb316dc556   2 weeks ago     134MB
> nginx                                latest     63eb316dc556   2 weeks ago     134MB
> k8s.gcr.io/kube-apiserver            v1.22.4    8fdcfcac0b01   4 weeks ago     119MB
> k8s.gcr.io/kube-proxy                v1.22.4    9c13f5c7b906   4 weeks ago     97.4MB
> k8s.gcr.io/kube-controller-manager   v1.22.4    c748f2606342   4 weeks ago     113MB
> k8s.gcr.io/kube-scheduler            v1.22.4    0b8df59b0199   4 weeks ago     49.3MB
> gcr.io/k8s-minikube/kicbase          v0.0.28    c3db8807ea16   2 months ago    981MB
> docker/desktop-vpnkit-controller     v2.0       2edf9c994f19   7 months ago    19.2MB
> docker/desktop-storage-provisioner   v2.0       c027a58fa0bb   7 months ago    39.8MB
> k8s.gcr.io/pause                     3.4.1      d055819ed991   11 months ago   484kB
> k8s.gcr.io/coredns/coredns           v1.8.0     1a1f05a2cd7c   14 months ago   39.3MB
> k8s.gcr.io/etcd                      3.4.13-0   05b738aa1bc6   15 months ago   312MB
> ```
> 
> I added the IPs to the docker configurations
> 
> ```
> {
>   "features": {
>     "buildkit": true
>   },
>   "insecure-registries": [
>     "10.103.5.200",
>     "10.0.0.16"
>   ],
>   "experimental": false,
>   "builder": {
>     "gc": {
>       "enabled": true,
>       "defaultKeepStorage": "20GB"
>     }
>   }
> }
> ```

Did you push the image into Minikube's internal registry? That would have been something like:
```
docker push 10.0.0.16:8888/nginx-signed
```
You could confirm that it is there with something like:
```
crane ls 10.0.0.16:8888/nginx-signed
```

**Comment by maorkuriel** [comment]
I did push the images into minikube's internal registry.
You can see the image `10.0.0.16:8888/nginx-signed          latest     63eb316dc556   2 weeks ago     134MB`

I will run through the steps again tomorrow and update you on the results.

**Comment by dlorenc** [comment]
> I did push the images into minikube's internal registry. You can see the image `10.0.0.16:8888/nginx-signed latest 63eb316dc556 2 weeks ago 134MB`

I think there might be some confusion between minikube's local daemon and minikube's local registry here. The "docker images" command only shows what's in the daemon. You'd need to `docker push` into the registry first.

**Comment by maorkuriel** [comment]
I ran the command `docker push "$HOST_IP":8888/nginx-unsigned` 
for both images ( signed and un-signed) as instructed by @bradbeck .

I wiped my env clean so I cant check it today, I will run the steps again tomorrow and update you on the results.

**Comment by bradbeck** [comment]
My upload connection is very slow, so I tend avoid pushing images to remote registries if possible.

The following modification of the above example uses `ttl.sh` and is hopefully less confusing and less error prone.

# Example image signature verification

Setup minikube and Kyverno.

```bash
make setup-minikube
make setup-kyverno
```

Pick a unique repository name to use on `ttl.sh`.

```bash
export REPO_NAME=bradbeck # <change this to something unique to you>
export REPOSITORY=ttl.sh/"$REPO_NAME"
```

Generate a key pair that we can use for signing and verifying images.

```bash
cosign generate-key-pair
```

Modify the Kyverno `verify-image` cluster policy to only allow images signed by our private key from above (`cosign.key`).

```bash
cat <<EOF | kubectl apply -f -
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image
spec:
  validationFailureAction: enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: verify-image
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
      - image: "*"
        key: |-
          -----BEGIN PUBLIC KEY-----
          <put your cosign.pub here>
          -----END PUBLIC KEY-----
EOF
```

Test that the cluster policy is working by trying to run `nginx`.

```bash
$ kubectl run nginx --image=nginx
Error from server: admission webhook "mutate.kyverno.svc-fail" denied the request: 

resource Pod/default/nginx was blocked due to the following policies

verify-image:
  verify-image: 'image signature verification failed for docker.io/nginx:latest: signature
    mismatch'
```

Pull the `nginx` image so we can push it the `ttl.sh` registry.

```bash
docker pull nginx:latest
docker tag nginx:latest "$REPOSITORY"/nginx-unsigned
docker push "$REPOSITORY"/nginx-unsigned
docker tag nginx:latest "$REPOSITORY"/nginx-signed
docker push "$REPOSITORY"/nginx-signed
```

Sign `.../nginx-signed` with our private key.

```bash
cosign sign --key cosign.key "$REPOSITORY"/nginx-signed
```

Confirm that `.../nginx-unsigned` doesn't have a signature associated with it in
the registry.

```bash
$ crane ls "$REPOSITORY"/nginx-unsigned
latest
```

Confirm that `.../nginx-signed` does have a signature associated with it in
the registry.

```bash
$ crane ls "$REPOSITORY"/nginx-signed
sha256-f3d58e8e62f8e897e13e60fcef9802a6de34c6adc83aa18ca5397fa7d6121a0b.sig
latest
```

Attempt to run the unsigned image.

```bash
$ kubectl run nginx --image="$REPOSITORY"/nginx-unsigned
Error from server: admission webhook "mutate.kyverno.svc-fail" denied the request: 

resource Pod/default/nginx was blocked due to the following policies

verify-image:
  verify-image: 'image signature verification failed for ttl.sh/bradbeck/nginx-unsigned:latest:
    signature mismatch'
```

Attempt to run the signed image.

```bash
$ kubectl run nginx --image="$REPOSITORY"/nginx-signed
pod/nginx created
```

## References

* <https://kyverno.io/docs/writing-policies/verify-images/>
* <https://github.com/sigstore/cosign#sign-a-container-and-store-the-signature-in-the-registry>

**Comment by maorkuriel** [comment]
Thank you, @bradbeck. This flow worked with no issues and ran smoothly.
