### ISSUE TITLE
Increase quality of README

### ISSUE THREAD

**Issue by trmiller** [thesecuresoftwarefactory/ssf#16]
Need to have a professional README.  
Follow standard template, with helpful images, and recognizable layout

**Comment by maorkuriel** [comment]
Some more tools/guides to make a more attractive GitHub readme page:
https://rahuldkjain.github.io/gh-profile-readme-generator/
https://rahuldkjain.github.io/gh-profile-readme-generator/addons
https://aboutmonica.com/blog/how-to-create-a-github-profile-readme
