### ISSUE TITLE
20-spire-setup.sh ends with rpc error

### ISSUE THREAD

**Issue by maorkuriel** [thesecuresoftwarefactory/ssf#36]
**Describe the bug**
When running the 20-spire-setup.sh script the script ends with the following error message
Waiting for client pods in default...
+ sleep 1
++ kubectl get pods --namespace default -l app=client -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}'
+ [[ True != \T\r\u\e ]]
++ kubectl get pods '-o=jsonpath={.items[0].metadata.name}' -l app=client
+ kubectl exec -it client-6c8cc85ccc-6t2mh -- /bin/sh -c '/opt/spire/bin/spire-agent api fetch -socketPath /run/spire/sockets/agent.sock'
rpc error: code = PermissionDenied desc = no identity issued
command terminated with exit code 1

**To Reproduce**
1. setup a clean env, and run the scripts in the instructed order

**Desktop (please complete the following information):**
 - OS:  Mac M1 MacOS Montery v12.0.1

**Additional context**
When I run the same command from the script manually it provides the following output
❯ kubectl exec -it \
  $(kubectl get pods -o=jsonpath='{.items[0].metadata.name}' -l app=client) \
  -- /bin/sh -c "/opt/spire/bin/spire-agent api fetch -socketPath /run/spire/sockets/agent.sock"
Received 1 svid after 70.718792ms

SPIFFE ID:		spiffe://example.org/ns/default/sa/default
SVID Valid After:	2021-11-03 08:13:38 +0000 UTC
SVID Valid Until:	2021-11-03 09:13:48 +0000 UTC
CA #1 Valid After:	2021-11-03 08:13:07 +0000 UTC
CA #1 Valid Until:	2021-11-04 08:13:17 +0000 UTC

 
❯ kubectl logs -n spire spire-agent-nqnv6
time="2021-11-03T08:13:32Z" level=warning msg="Current umask 0022 is too permissive; setting umask 0027"
time="2021-11-03T08:13:32Z" level=info msg="Starting agent with data directory: \"/run/spire\""
time="2021-11-03T08:13:32Z" level=info msg="Plugin loaded" external=false plugin_name=memory plugin_type=KeyManager subsystem_name=catalog
time="2021-11-03T08:13:32Z" level=info msg="Plugin loaded" external=false plugin_name=k8s plugin_type=WorkloadAttestor subsystem_name=catalog
time="2021-11-03T08:13:32Z" level=info msg="Plugin loaded" external=false plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog
time="2021-11-03T08:13:32Z" level=info msg="Plugin loaded" external=false plugin_name=k8s_sat plugin_type=NodeAttestor subsystem_name=catalog
time="2021-11-03T08:13:32Z" level=info msg="Bundle loaded" subsystem_name=attestor trust_domain_id="spiffe://example.org"
time="2021-11-03T08:13:32Z" level=debug msg="No pre-existing agent SVID found. Will perform node attestation" path=/run/spire/agent_svid.der subsystem_name=attestor
time="2021-11-03T08:13:33Z" level=info msg="SVID is not found. Starting node attestation" subsystem_name=attestor trust_domain_id="spiffe://example.org"
time="2021-11-03T08:13:33Z" level=info msg="Node attestation was successful" spiffe_id="spiffe://example.org/spire/agent/k8s_sat/demo-cluster/3b40084e-e095-4848-900e-34b387cb51af" subsystem_name=attestor trust_domain_id="spiffe://example.org"
time="2021-11-03T08:13:33Z" level=info msg="Starting Workload and SDS APIs" subsystem_name=endpoints
time="2021-11-03T08:13:34Z" level=debug msg="Starting checker" name=agent subsystem_name=health
time="2021-11-03T08:13:34Z" level=info msg="Serving health checks" address="0.0.0.0:8080" subsystem_name=health
time="2021-11-03T08:13:45Z" level=debug msg="PID attested to have selectors" pid=9783 selectors="[type:\"unix\" value:\"uid:0\" type:\"unix\" value:\"user:root\" type:\"unix\" value:\"gid:0\" type:\"unix\" value:\"group:root\" type:\"unix\" value:\"supplementary_gid:0\" type:\"unix\" value:\"supplementary_group:root\" type:\"unix\" value:\"supplementary_gid:1\" type:\"unix\" value:\"supplementary_group:bin\" type:\"unix\" value:\"supplementary_gid:2\" type:\"unix\" value:\"supplementary_group:daemon\" type:\"unix\" value:\"supplementary_gid:3\" type:\"unix\" value:\"supplementary_group:sys\" type:\"unix\" value:\"supplementary_gid:4\" type:\"unix\" value:\"supplementary_group:adm\" type:\"unix\" value:\"supplementary_gid:6\" type:\"unix\" value:\"supplementary_group:disk\" type:\"unix\" value:\"supplementary_gid:10\" type:\"unix\" value:\"supplementary_group:wheel\" type:\"unix\" value:\"supplementary_gid:11\" type:\"unix\" value:\"supplementary_group:floppy\" type:\"unix\" value:\"supplementary_gid:20\" type:\"unix\" value:\"supplementary_group:dialout\" type:\"unix\" value:\"supplementary_gid:26\" type:\"unix\" value:\"supplementary_group:tape\" type:\"unix\" value:\"supplementary_gid:27\" type:\"unix\" value:\"supplementary_group:video\" type:\"k8s\" value:\"sa:default\" type:\"k8s\" value:\"ns:default\" type:\"k8s\" value:\"node-name:minikube\" type:\"k8s\" value:\"pod-uid:0596964d-ecca-4ad7-9bd3-ead08d028794\" type:\"k8s\" value:\"pod-name:client-6c8cc85ccc-6t2mh\" type:\"k8s\" value:\"container-name:client\" type:\"k8s\" value:\"pod-image-count:1\" type:\"k8s\" value:\"pod-init-image-count:0\" type:\"k8s\" value:\"container-image:docker-pullable://gcr.io/spiffe-io/spire-agent@sha256:e1e299ee1ad2bc33c67610a90025f04a31a9ec9f8332c9a855d9d094c95573f9\" type:\"k8s\" value:\"container-image:gcr.io/spiffe-io/spire-agent:1.0.0\" type:\"k8s\" value:\"pod-image:gcr.io/spiffe-io/spire-agent:1.0.0\" type:\"k8s\" value:\"pod-image:docker-pullable://gcr.io/spiffe-io/spire-agent@sha256:e1e299ee1ad2bc33c67610a90025f04a31a9ec9f8332c9a855d9d094c95573f9\" type:\"k8s\" value:\"pod-label:pod-template-hash:6c8cc85ccc\" type:\"k8s\" value:\"pod-label:app:client\" type:\"k8s\" value:\"pod-owner:ReplicaSet:client-6c8cc85ccc\" type:\"k8s\" value:\"pod-owner-uid:ReplicaSet:0c5a6266-0514-4066-8f05-fbedebff3da4\"]" subsystem_name=workload_attestor
time="2021-11-03T08:13:45Z" level=error msg="No identity issued" method=FetchX509SVID pid=9783 registered=false service=WorkloadAPI subsystem_name=endpoints
time="2021-11-03T08:13:48Z" level=debug msg="Entry created" entry=77be5457-c4d7-4634-bc0b-75334d405bfb selectors_added=3 spiffe_id="spiffe://example.org/ns/spire/sa/spire-agent" subsystem_name=cache_manager
time="2021-11-03T08:13:48Z" level=debug msg="Entry created" entry=1bf0f8db-6c90-4183-8a72-238a9a864fc5 selectors_added=2 spiffe_id="spiffe://example.org/ns/default/sa/default" subsystem_name=cache_manager
time="2021-11-03T08:13:48Z" level=debug msg="Renewing stale entries" count=2 limit=500 subsystem_name=manager
time="2021-11-03T08:13:48Z" level=info msg="Renewing X509-SVID" spiffe_id="spiffe://example.org/ns/spire/sa/spire-agent" subsystem_name=manager
time="2021-11-03T08:13:48Z" level=info msg="Renewing X509-SVID" spiffe_id="spiffe://example.org/ns/default/sa/default" subsystem_name=manager
time="2021-11-03T08:13:48Z" level=debug msg="SVID updated" entry=77be5457-c4d7-4634-bc0b-75334d405bfb spiffe_id="spiffe://example.org/ns/spire/sa/spire-agent" subsystem_name=cache_manager
time="2021-11-03T08:13:48Z" level=debug msg="SVID updated" entry=1bf0f8db-6c90-4183-8a72-238a9a864fc5 spiffe_id="spiffe://example.org/ns/default/sa/default" subsystem_name=cache_manager

**Comment by bradbeck** [comment]
@maorkuriel https://github.com/thesecuresoftwarefactory/ssf/pull/29 should help alleviate this.

**Comment by maorkuriel** [comment]
Thanks @bradbeck
