### ISSUE TITLE
Buildpacks demo doesn't work

### ISSUE THREAD

**Issue by mlieberman85** [thesecuresoftwarefactory/ssf#40]
https://github.com/thesecuresoftwarefactory/ssf/blob/0f840cc533487026afd7020575e250101ba699ae/resources/tekton/examples/buildpacks/buildpacks.sh#L5

This isn't a valid git command. Some people alias `rev-parse --show-toplevel` but we can't rely on that. @rgreinho 

In addition to that the yaml includes the pipelinerun but only runs an apply which means that it won't generate a new pipeline.

**Comment by rgreinho** [comment]
I believe this was addressed as part of #50.
